### ISSUE TITLE
你好 运行微信开发者工具报错啊

### ISSUE THREAD

**Issue by shenmashi** [coolhwm/leshare-seller-wepy#46]
request:fail invalid url "null/auth/session?code=071VQ1e320GwkM0Jckd32UjVd32VQ1ea&app_code=null"

这是哪里的问题

**Comment by shenmashi** [comment]
你的代码是否出售？

**Comment by coolhwm** [comment]
你好，由于后端暂未提供测试服务，后端地址没有配置在源代码中，故暂时无法登陆
代码已经开源，无需购买，建议通过模拟数据的方式，复用样式及组件
商务合作可邮件联系

**Comment by coolhwm** [comment]
@shenmashi  后端Mock接口已开放
