### ISSUE TITLE
可以建群  共同维护吗

### ISSUE THREAD

**Issue by shenmashi** [coolhwm/leshare-seller-wepy#47]
可以建群  共同维护吗

**Comment by shenmashi** [comment]
QQ 742819177  微信同

**Comment by coolhwm** [comment]
有共同维护意向，可以参与，我可以提供测试环境，由于后端不开源，恐怕难以满足您的需求

**Comment by Akiq2016** [comment]
@coolhwm 想请教一下 使用wepy的话 列表页的异步数据加载，需要手动调用$apply方法，而随着数据增多，脏检查的时间也越久，导致页面加载卡顿。你是怎么解决的？

**Comment by coolhwm** [comment]
@Akiq2016  目前还没遇到这个问题，wepy本身的脏检查应该没有问题，数据量尽量还是控制一下
如果是用wepy-redux卡顿的话，升级下最新版本就好了

**Comment by coolhwm** [comment]
@shenmashi  后端Mock接口已开放
