### ISSUE TITLE
为什么我修改为自己的api地址还是报错？

### ISSUE THREAD

**Issue by yangpengfei** [coolhwm/leshare-seller-wepy#50]
页面还是不能正常跳转到首页。请问是否跟这个login_code有关呢？
![qq 20180323164127](https://user-images.githubusercontent.com/7697949/37819632-1a26471a-2eb9-11e8-80b7-b2d73beda1e3.png)

**Comment by coolhwm** [comment]
最新的接口应该是可以连接到mock后端的
```
globalData = {
      auth: {},
      shop: {},
      appCode: 'XXX',
      baseUrl: 'https://www.easy-mock.com/mock/5aa15ee0f6ed4a592fb5d6ec/leshare',
      version: 'v3.0.0'
    };
```

**Comment by yangpengfei** [comment]
谢谢，我是将你的接口地址更换成我自己写的啦。我在研究下。非常感谢
